# Java Maven CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

orbs:
  maven: circleci/maven@2.0.0

jobs:
  build:
    executor: maven/default
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:21.0.6
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          shell: /bin/bash
          command: |
            mkdir -p test-results
          when: always

      # run tests!
      - run: mvn integration-test
      - store_test_results:
          path: test-results

workflows:
  main:
    jobs:
      - build
